[package]
name = "moc3-example"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.11.1"
glam = "0.24.1"
image = "0.24.7"
moc3-rs = { path = "../moc3-rs" }
moc3-wgpu = { path = "../moc3-wgpu" }
pollster = "0.3.0"
wgpu = "0.17.1"
winit = "0.28.6"
