[package]
name = "moc3-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.13.1", features = ["extern_crate_alloc", "derive"] }
encase = { version = "0.6.1", features = ["glam"] }
glam = { version = "0.24.1", features = ["bytemuck"] }
image = "0.24.7"
moc3-rs = { path = "../moc3-rs" }
wgpu = "0.17.0"
